apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-argocd
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx-test-argocd
  template:
    metadata:
      labels:
        app: nginx-test-argocd
    spec:
      containers:
      - image: nginx:1.25.3
        name: nginx-test-argocd
        ports:
        - containerPort: 80
