replicaCount: 1

image:
  repository: hashicorpnomad/counter-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v3"

service:
  type: ClusterIP
  port: 9001

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

ingress: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
